# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# https://aka.ms/yaml

queue: 'Hosted VS2017'
variables:
  buildConfiguration: 'Release'
  buildPlatform: 'Any CPU'
  solution: '**/*.sln'
steps:

- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

#- task: PublishSymbols@1
#  inputs:
#    searchPattern: '**/bin/$(buildConfiguration)/*.pdb'
#- task: CopyFiles@2
#  inputs:
#    contents: '**/bin/$(buildConfiguration)/**'
#    targetFolder: '$(build.artifactStagingDirectory)'
#- task: PublishBuildArtifacts@1
